development:
  adapter: mysql2
  encoding: utf8
  database: cake_dev
  host: localhost
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  database: cake_test
  host: localhost
  username: root
  password:

production:
  adapter: mysql2
  encoding: utf8
  database: cake_prod
  host: localhost
  username: root
  password:
